/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurant;

/**
 *
 * @author Aupee
 */
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
public class Main extends javax.swing.JFrame {
Connection cn;
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.setLocationRelativeTo(null);
        btnAdd.setEnabled(false);
        btnRemove.setEnabled(false);
        connection();
        loadrecord(jTable1);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnPay = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtID = new javax.swing.JLabel();
        txtFood = new javax.swing.JLabel();
        txtPrice = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtqty = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSum = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        jTable1.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Food ID", "Food Name", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 360, 159));

        btnAdd.setBackground(new java.awt.Color(204, 204, 204));
        btnAdd.setFont(new java.awt.Font("Georgia Pro Black", 1, 18)); // NOI18N
        btnAdd.setText("Add to Cart");
        btnAdd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        btnAdd.setBorderPainted(false);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 150, 40));

        jTable3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        jTable3.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Food ID", "Food Name", "Quantity", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);
        if (jTable3.getColumnModel().getColumnCount() > 0) {
            jTable3.getColumnModel().getColumn(0).setResizable(false);
            jTable3.getColumnModel().getColumn(1).setResizable(false);
            jTable3.getColumnModel().getColumn(2).setResizable(false);
            jTable3.getColumnModel().getColumn(3).setResizable(false);
        }

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 350, 159));

        jLabel1.setFont(new java.awt.Font("Georgia Pro Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CART");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, -1, -1));

        btnPay.setBackground(new java.awt.Color(204, 204, 204));
        btnPay.setFont(new java.awt.Font("Georgia Pro Black", 1, 18)); // NOI18N
        btnPay.setText("Pay");
        btnPay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        btnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayActionPerformed(evt);
            }
        });
        getContentPane().add(btnPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 490, 70, 40));

        btnRemove.setBackground(new java.awt.Color(0, 0, 0));
        btnRemove.setForeground(new java.awt.Color(255, 255, 255));
        btnRemove.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aupee\\Documents\\NetBeansProjects\\Restaurant\\Project Images\\delete.png")); // NOI18N
        btnRemove.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        getContentPane().add(btnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 490, 70, 40));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aupee\\Documents\\NetBeansProjects\\Restaurant\\Project Images\\Back.png")); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Georgia Pro Black", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Food Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));

        jLabel3.setFont(new java.awt.Font("Georgia Pro Black", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Price:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, -1));

        jLabel6.setFont(new java.awt.Font("Georgia Pro Black", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ID:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 40, -1));

        txtID.setFont(new java.awt.Font("Georgia Pro Black", 1, 16)); // NOI18N
        txtID.setForeground(new java.awt.Color(255, 255, 255));
        txtID.setText("0");
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 80, 40));

        txtFood.setFont(new java.awt.Font("Georgia Pro Black", 1, 16)); // NOI18N
        txtFood.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtFood, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 240, 40));

        txtPrice.setFont(new java.awt.Font("Georgia Pro Black", 1, 16)); // NOI18N
        txtPrice.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 80, 60));

        jLabel8.setFont(new java.awt.Font("Georgia Pro Black", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Quantity");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, -1, -1));

        txtqty.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        txtqty.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtqty.setText("1");
        getContentPane().add(txtqty, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, 110, 40));

        jLabel4.setFont(new java.awt.Font("Georgia Pro Black", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TOTAL:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 410, -1, -1));

        txtSum.setFont(new java.awt.Font("Georgia Pro Black", 1, 16)); // NOI18N
        txtSum.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtSum, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, 90, 40));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents
     
    public void connection()
    {
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbrms", "root", "" );
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, "Connection is close!");
        }
    }
    
    public void loadrecord(JTable table)
    {
        connection();
        try
        {
            PreparedStatement ps = cn.prepareStatement("Select *from tblfoods");
            ResultSet rs = ps.executeQuery();
            DefaultTableModel model = (DefaultTableModel)table.getModel();
            model.setRowCount(0);
            Object [] row;
            while (rs.next())
            {
                row = new Object[3];
                row [0] = rs.getInt(1);
                row [1] = rs.getString(2);
                row [2] = rs.getInt(3);
                model.addRow(row);
            }
            cn.close();
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }
    
    public void loadrecord1(JTable table)
    {
        connection();
        try
        {
            PreparedStatement ps = cn.prepareStatement("Select *from tblcart");
            ResultSet rs = ps.executeQuery();
            DefaultTableModel model = (DefaultTableModel)table.getModel();
            model.setRowCount(0);
            Object [] row;
            while (rs.next())
            {
                row = new Object[4];
                row [0] = rs.getInt(1);
                row [1] = rs.getString(2);
                row [2] = rs.getString(3);
                row [3] = rs.getInt(4);
                model.addRow(row);
            }
            cn.close();
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }
    
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        btnAdd.setEnabled(true);
        int rowIndex = jTable1.getSelectedRow();
        txtID.setText(jTable1.getValueAt(rowIndex, 0).toString());
        txtFood.setText(jTable1.getValueAt(rowIndex, 1).toString());
        txtPrice.setText(jTable1.getValueAt(rowIndex, 2).toString());
         
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        new Option().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed
       new Pay().setVisible(true);
    }//GEN-LAST:event_btnPayActionPerformed

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        btnRemove.setEnabled(true);
        int rowIndex = jTable3.getSelectedRow();
        txtID.setText(jTable3.getValueAt(rowIndex, 0).toString());
        txtFood.setText(jTable3.getValueAt(rowIndex, 1).toString());
        txtPrice.setText(jTable3.getValueAt(rowIndex, 3).toString());
        
    }//GEN-LAST:event_jTable3MouseClicked

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        connection();
        int i = Integer.parseInt(txtSum.getText());
        int ii = Integer.parseInt(txtPrice.getText());
        int t = i - ii;
        String f = String.valueOf(t);
        txtSum.setText(f);
        
        
        try
        {
            String id = txtID.getText();
            if (id.equals("0"))
            {
                JOptionPane.showMessageDialog(null, "No Data Selected");
            }
            else
            {
                PreparedStatement ps = cn.prepareStatement("delete from tblcart where id like '"+id+"'");
                ps.execute();
                cn.close();
                
                loadrecord1(jTable3);
                txtID.setText("0");
                txtFood.setText("");
                txtPrice.setText("");
            }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        connection();
        String id = txtID.getText();
        String fud = txtFood.getText();
        String price = txtPrice.getText();

        int prices = Integer.parseInt(price);
        int qty = Integer.parseInt(txtqty.getText());
        int total = prices * qty;
        String tot = String.valueOf(total);
        String Quant = String.valueOf(qty);

        try
        {
            PreparedStatement ps = cn.prepareStatement("insert into tblcart (id, Foods, Quantity, Price)values (?,?,?,?)");
            ps.setString(1, id);
            ps.setString(2, fud);
            ps.setString(3, Quant);
            ps.setString(4, tot);

            ps.execute();
            loadrecord(jTable1);
            cn.close();

            txtID.setText("0");
            txtFood.setText("");
            txtPrice.setText("");
            loadrecord1(jTable3);
            int sum =+ total;
            txtSum.setText(""+sum);

        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnPay;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JLabel txtFood;
    private javax.swing.JLabel txtID;
    private javax.swing.JLabel txtPrice;
    private javax.swing.JLabel txtSum;
    private javax.swing.JTextField txtqty;
    // End of variables declaration//GEN-END:variables
}
